### ISSUE TITLE
OTBM_TILE cannot contain aid/uid

### ISSUE THREAD

**Issue by Sajgon** [Inconcessus/OTBM2JSON#5]
Looks like Tiles can't hold action ids and unique ids, those tiles that does, seems to become OTBM_ITEM of type 6 instead of 5(OTBM_TILE).

I haven't found a fix for it yet.

**Comment by Inconcessus** [comment]
Thanks! I will check soon!

**Comment by Inconcessus** [comment]
I tried saving a single dirt tile with an action & unique ID. From RME it is stored to OTBM as:

    ...
    fe 04 00 03 00 03 07
        fe 05 f1 fb
            fe 06 67 00 04 e8 03 05 d0 07 ff
        ff
    ff
    ...

Which is nested `OTBM_TILE_AREA`, `OTBM_TILE`, `OTBM_ITEM`. Action identifier (`0x04` of `0x03E8`) and Unique identifier (`0x05` of `07D0`). The library writes the same information back. Is it not supposed to be this way? Perhaps you have a simple example file showing the problem.

**Comment by Sajgon** [comment]
How to reproduce
1. Download latest commit
2. Open void.otbm with mapeditor
3. add actionId or uniqueId to any tile and save
4. run `node example`
5. open chess.otbm 

you will now see tiles with actionid or uniqueid are not being replaced, my conclusion is some tiles/items with special attributes does not work replace IDs

**Comment by Inconcessus** [comment]
We found out that tiles with an action or unique identifiers are saved by RME as items. This means that the identifier of the tile is not set as the `tileid` of the tile node, but of that of the `id` of the first item of its children. In a conversion script, you will therefore have to modify the `id` attribute of the first item.

E.g. add:

    // Tile identifier is undefined because of an aid/uid.. it is probably the first item
    if(x.tileid === undefined) {
        if(x.x & 1 ^ x.y & 1) {
            x.items[0].id = BLACK_TILE;
        } else {
            x.items[0].id = WHITE_TILE;
        }
    }

Won't fix in the library because this is an inconsistency in OTBM.
